SELECT I.ID_INSTALACION CLIENTE, C.NOMBRES NOMBRE,
    RTRIM(RTRIM(LTRIM(V.NOMBRE_VIA))||' '||P.NUMERO||' '||P.NUMERO_DEPTO) DIRECCION,
    C.FONO TELEFONO,
    M.NUMERO_SERIE_MEDIDOR NUM_MEDIDOR, L.NOMBRE_LOCALIDAD CIUDAD,
    RTRIM(R.LECTURA) ult_lectura, E.DES_ESTADO_CORTE ESTADO_CORTE,
    T.DESC_ESTADO_INST ESTADO_INSTALACION,
    A.DESC_COD_MARCA_MEDIDOR MARCA, B.DESC_COD_MODELO_MEDIDOR MODELO,
    M.DIAMETRO_MEDIDOR DIAMETRO,
    I.COD_GRUPO_FACTURACION GRUPO_FACTURACION, R.FECHA_LECTURA FECHA_LECTURA,
    SUM(R.CONSUMO_FACTURADO+R.CONSUMO_GENERAL+R.SOBRECONSUMO)CONSUMO
FROM INSTALACION I, PROPIEDAD P, P_VIA V,
    CLIENTE C, INSTALACION_MEDIDOR M, P_LOCALIDAD L, REGISTRO_FISICO R,
    P_ESTADO_CORTE_INSTALACION E, P_ESTADO_INSTALACION T,
    P_MARCA_MEDIDOR A, P_MODELO_MEDIDOR B
WHERE i.id_instalacion = replace(replace(replace(msg.payload.id,'.'),','),'%2C') and (M.FECHA_RETIRO=0
AND R.FECHA_FACTURACION&gt;0
AND R.FECHA_LECTURA=(SELECT MAX(R1.FECHA_LECTURA) 
                     FROM REGISTRO_FISICO R1
                     WHERE (R1.FECHA_FACTURACION&gt;0
                     AND R1.COD_CLAVE_LECTURA NOT IN ('III', 'RRR')
                     AND R1.ID_INSTALACION=I.ID_INSTALACION)))
AND  ((P.COD_VIA=V.COD_VIA)
AND (I.ID_PROPIEDAD=P.ID_PROPIEDAD)
AND (I.RUT_CLIENTE=C.RUT_CLIENTE(+))
AND (I.ID_INSTALACION=M.ID_INSTALACION)
AND (I.COD_LOCALIDAD=L.COD_LOCALIDAD)
AND (I.ID_INSTALACION=R.ID_INSTALACION)
AND (I.ESTADO_CORTE=E.ESTADO_CORTE)
AND (I.ESTADO_INSTALACION=T.ESTADO_INSTALACION)
AND (M.COD_MARCA_MEDIDOR=A.COD_MARCA_MEDIDOR)
AND (M.COD_MODELO_MEDIDOR=B.COD_MODELO_MEDIDOR))
GROUP BY I.ID_INSTALACION, C.NOMBRES, 
RTRIM(LTRIM(V.NOMBRE_VIA))||' '||P.NUMERO||' '||P.NUMERO_DEPTO, 
C.FONO, M.NUMERO_SERIE_MEDIDOR, 
L.NOMBRE_LOCALIDAD, 
R.LECTURA, E.DES_ESTADO_CORTE, 
T.DESC_ESTADO_INST, A.DESC_COD_MARCA_MEDIDOR, 
B.DESC_COD_MODELO_MEDIDOR, 
M.DIAMETRO_MEDIDOR, I.COD_GRUPO_FACTURACION, 
R.FECHA_LECTURA